// nobodywho_flutter.js — FRB-compatible loader that adapts our Emscripten
// output to flutter_rust_bridge's web loader protocol.
//
// flutter_rust_bridge/frb_dart/lib/src/wasm_module/_web.dart expects:
//
//     <script src="pkg/nobodywho_flutter.js">
//     // after load:
//     const mod = await wasm_bindgen({module_or_path: 'pkg/nobodywho_flutter_bg.wasm'});
//     mod.rust_arc_increment_strong_count_…(ptr);
//
// i.e. wasm-pack's `--target no-modules` shape: a callable global named
// `wasm_bindgen` that, after its init promise resolves, also exposes each
// wasm export as a property on itself.
//
// Our build produces `nobodywho_flutter_web.{js,wasm}` via Emscripten's
// `-sMODULARIZE=1 -sEXPORT_NAME='createNobodyWhoModule'`, which is a
// completely different shape (factory returning a Promise<Module>, with
// exports ON that Module, not on the factory). This shim ties them together:
//
//   1. Inlines the full Emscripten-generated JS below (populated by the
//      prepare-web-assets step — see
//      `nobodywho/flutter/nobodywho/tool/prepare_web_assets.sh`).
//   2. Defines `wasm_bindgen(opts)` as a function that calls
//      `createNobodyWhoModule` and, when it resolves, copies the Module's
//      exports onto `wasm_bindgen` itself so FRB's `wasmModule.method(...)`
//      lookups hit real wasm exports.
//   3. Maps FRB's `{module_or_path: '..._bg.wasm'}` request to Emscripten's
//      `locateFile` hook so the runtime fetches the right .wasm file.
//
// This file is regenerated by the prepare-web-assets step; edits below the
// `/* === EMSCRIPTEN GLUE === */` marker are overwritten on every build.

(function (globalScope) {
  // Factory name comes from -sEXPORT_NAME in nobodywho/flutter/rust/build.rs.
  const FACTORY = 'createNobodyWhoModule';

  function wasm_bindgen(opts) {
    const moduleOrPath = opts && opts['module_or_path'];
    const factory = globalScope[FACTORY];
    if (typeof factory !== 'function') {
      return Promise.reject(new Error(
        'nobodywho_flutter shim: expected globalScope.' + FACTORY +
        ' to be defined by the inlined Emscripten glue'));
    }
    // Pre-fetch the wasm and hand the bytes to Emscripten as `wasmBinary`.
    // We can't rely on Emscripten's built-in fetch path here: when this
    // script is injected dynamically by flutter_rust_bridge's loader
    // (rather than declared as a <script src=…> at parse time), browsers
    // set `document.currentScript` to null inside the inlined glue, so
    // Emscripten's `scriptDirectory` falls back to '' and the wasm request
    // goes to the host root instead of `pkg/`. Pre-fetching sidesteps that
    // entirely and also lets us honour the exact URL FRB asked for.
    if (!moduleOrPath) {
      return Promise.reject(new Error(
        'nobodywho_flutter shim: expected opts.module_or_path'));
    }
    return fetch(moduleOrPath)
      .then(function (resp) {
        if (!resp.ok) {
          throw new Error(
            'nobodywho_flutter shim: failed to fetch ' + moduleOrPath +
            ' (HTTP ' + resp.status + ')');
        }
        return resp.arrayBuffer();
      })
      .then(function (buf) { return factory({wasmBinary: new Uint8Array(buf)}); })
      .then(function (mod) {
      // Expose every Emscripten export as a property on wasm_bindgen itself
      // so FRB's generated `@JS('wasm_bindgen')` binding can do
      // `wasm_bindgen.rust_arc_increment_…(ptr)` directly.
      //
      // Emscripten prefixes every C-exported wasm function with a single
      // leading underscore (classic asm-style mangling); wasm-pack, the
      // convention FRB's codegen targets, omits that prefix. Expose each
      // function-valued export under BOTH its underscore and un-prefixed
      // names so either calling convention resolves.
      for (const k of Object.keys(mod)) {
        wasm_bindgen[k] = mod[k];
        if (k.startsWith('_') && typeof mod[k] === 'function') {
          const unprefixed = k.slice(1);
          if (!(unprefixed in wasm_bindgen)) {
            wasm_bindgen[unprefixed] = mod[k];
          }
        }
      }
      return mod;
    });
  }

  // Dart's `dart:js_interop` maps a declaration like
  //     extension type _JSWasmBindgen(JSObject _) implements JSObject {
  //       external JSPromise call(JSAny? arg);
  //     }
  // to JS `foo.call(x)`, which is `Function.prototype.call`: it sets
  // `this = x` and passes no actual arguments. FRB uses exactly that
  // extension type to invoke the loader, so the positional arg shows up as
  // `thisArg` instead of `opts`. Overriding `.call` on our function lets us
  // accept that calling convention without requiring a patch to FRB.
  wasm_bindgen.call = function (thisArg) {
    return wasm_bindgen(thisArg);
  };

  globalScope.wasm_bindgen = wasm_bindgen;
})(typeof window !== 'undefined' ? window : globalThis);

/* === EMSCRIPTEN GLUE ===
 * The remainder of this file is populated by the prepare-web-assets step.
 * Until that step runs, `wasm_bindgen(...)` rejects with
 * "expected globalScope.createNobodyWhoModule to be defined".
 */
